#!/bin/bash

set -x

VERSION=1
SERVICE="bitwarden_rs"

. /usr/share/univention-join/joinscripthelper.lib
. /usr/share/univention-appcenter/joinscripthelper.sh
. /usr/share/univention-lib/base.sh

joinscript_init
eval "$(ucr shell)"

ucs_addServiceToLocalhost "${SERVICE}" "$@"

# add custom ports to firewall
ucr set \
	security/packetfilter/package/bitwarden_rs/tcp/8567/all="ACCEPT" \
	security/packetfilter/package/bitwarden_rs/tcp/8567/all/en="bitwarden_rs http" \
	security/packetfilter/package/bitwarden_rs/tcp/8678/all="ACCEPT" \
	security/packetfilter/package/bitwarden_rs/tcp/8678/all/en="bitwarden_rs https" \
[ -x "/etc/init.d/univention-firewall" ] && invoke-rc.d univention-firewall restart


joinscript_save_current_version
exit 0
