#!/bin/bash
# exit when any command fails
set -e

# keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
# echo an error message before exiting
trap 'echo "\"${last_command}\" command stopped with exit code $?."' EXIT

eval "$(ucr shell)"

DATADIR="/var/lib/bitwarden_rs"

mkdir -p $DATADIR
